#! /bin/bash
# cd /mnt/host/2_Scripts
clear

# Which?
WHICH_PPIname="coFam_sph_SNVTA_L_coSRvSN_psy_DisN"
WHICH_FLModel=ci3Hit
WHICH_AnalysisThread=s4FullCardiacWithDeriv
WHICH_Landmarks=5
WHICH_Cons=(0001)


# Paths
PATH_to_HpcTemplate=/mnt/host/1a_Data_CreateHPCTemplate
PATH_to_SubData=/mnt/host/2_Data_AdjustCons
WHICH_AdjustConMethod=Landmarks
SubjList=${PATH_to_SubData}"/SubjList_"${WHICH_FLModel}".txt"

echo " ------------------------------------------------------------------ "
echo `date`
echo "Data location: "$PATH_to_SubData
echo "Subject list used: "$SubjList
echo " --- "
echo "Contrast adjustment method: " ${WHICH_AdjustConMethod}
echo "First level model: "${WHICH_AnalysisThread}"_"${WHICH_FLModel}
echo "PPI model requested: "${WHICH_PPIname}
echo ' '

##########################################################################################
# MISC INSTRUCTIONS
##########################################################################################
#
# 
##########################################################################################

#SubjName=p01_CW

while read SubjName
	do 

	echo '###############################################################################'
	SubFol=${PATH_to_SubData}"/"${SubjName}
	SubFol_AdjustPars=${SubFol}"/"${WHICH_AdjustConMethod}${WHICH_Landmarks}
	SubFol_ForPPImodel=${SubFol_AdjustPars}"/"${WHICH_AnalysisThread}"_"${WHICH_FLModel}"/"${WHICH_PPIname}
	echo `date`
	echo  "Processing subject: ###${SubjName}### "
	echo "Folders & Details:"
	echo  ${SubFol}	
	echo  ${SubFol_AdjustPars}
	echo  ${SubFol_ForPPImodel}
	echo " "

	# Adjust all specified contrasts
	echo ${SubFol_ForPPImodel}
	for i in ${WHICH_Cons[*]}
		do
		echo '   Adjusting contrast '$i

		########################################################
		### Apply all parameters to masks and contrast images
		###  Output: r_con_xxx.nii
		########################################################
		WarpImageMultiTransform 3 ${SubFol_ForPPImodel}"/con_"$i".nii" ${SubFol_ForPPImodel}"/r_con_"$i".nii" -R ${PATH_to_HpcTemplate}"/hc_template.nii.gz" ${SubFol_AdjustPars}"/"${SubjName}"_LM_Warp.nii.gz" ${SubFol_AdjustPars}"/"${SubjName}"_LM_Affine.txt"


	done

	echo "END of subject " $SubjName
done <$SubjList

#############################################################################################
echo `date`


